### ISSUE TITLE
NoneType in johnny-import

### ISSUE THREAD

**Issue by agrieco** [edgebips/johnny#12]
I'm just trying to get things going.  I'm attempting my first import and am hitting this error.    I'm using ToS.

Any insights as to what I might be doing wrong?
thanks

~/johnny$ ./bin/johnny-import
Traceback (most recent call last):
  File "/home/agrieco/johnny/./bin/johnny-import", line 27, in <module>
    from johnny.base import chains as chainslib
  File "/home/agrieco/johnny/johnny/base/chains.py", line 39, in <module>
    from johnny.base import config as configlib
  File "/home/agrieco/johnny/johnny/base/config.py", line 14, in <module>
    from johnny.base.config_pb2 import Config, Account
  File "/home/agrieco/johnny/johnny/base/config_pb2.py", line 21, in <module>
    _INSTRUMENTTYPE = DESCRIPTOR.enum_types_by_name["InstrumentType"]
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'

**Comment by blais** [comment]
No idea. Looks like somehow pb is creating an empty DESCRIPTOR object. Did you install protobuf?

**Comment by agrieco** [comment]
thanks for the hint.  That was it.  For anyone else who finds this:  
I needed to execute:
```
protoc -I . --python_out . --proto_path . johnny/base/chains.proto
protoc -I . --python_out . --proto_path . johnny/base/config.proto
```
